# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJZFyuJ4hGaHVM_oD5CcdemKu57vCjRq
"""

from preprocess import main as pre
import joblib
import pandas as pd
import numpy as np


def main():
    # filename = 'final_test.csv'
    pre()
    clf = joblib.load("model.pkl")
    df = pd.read_csv('testing.csv')
    df.drop(['Unnamed: 0'], axis=1, inplace=True)
    df = df.dropna()
    columnsTitles = ['fit', 'body_type', 'category', 'weight', 'rating', 'height',
                     'age', 'bust_size', 'cup_size_start_in_cms', 'cup_size_end_in_cms']
    df = df.reindex(columns=columnsTitles)
    test = np.array(df)
    Y_pred = clf.predict(test)
    print(Y_pred)
    size = {0: 'XS', 1: 'S', 2: 'M', 3: 'L', 4: 'XL', 5: 'XXL'}
    x = np.vectorize(size.get)(Y_pred)
    return x


if __name__ == "__main__":
    main()
